export const degreesData = [
    {
        id: "D1",
        title: "Bachelor of Science Honours in Artificial Intelligence",
        subtitle: "University of Moratuwa",
        icon: "https://upload.wikimedia.org/wikipedia/en/6/60/University_of_Moratuwa_logo.png",
        image: "https://uom.lk/sites/default/files/civil/images/civil1_0.jpg",
        description: "Focuses on machine learning, robotics, and data science to build intelligent systems.",
        tag: "degree",
        isNew: true,
        views: 578000,
        interested: 78000,
        engaged: 18000,
    },
    {
        id: "D2",
        title: "Bachelor of Law",
        subtitle: "University of Colombo",
        icon: "https://upload.wikimedia.org/wikipedia/en/f/f9/Logo_of_the_University_of_Colombo.png",
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSmxehgYOh-DKY9DYpAnoPGG6JFCK1uGVt14g&s",
        description: "Covers legal theory, civil and criminal law, constitutional studies, and legal practice.",
        tag: "degree",
        views: 578000,
        interested: 78000,
        engaged: 18000,
    },
    {
        id: "D3",
        title: "Bachelor of Science in Computer Science",
        subtitle: "University of Colombo",
        icon: "https://upload.wikimedia.org/wikipedia/en/f/f9/Logo_of_the_University_of_Colombo.png",
        image: "https://dcfwfuaf91uza.cloudfront.net/residential/wp-content/uploads/Bachelor-of-Science-in-Computer-Science-General.jpg",
        description: "Offers deep insight into algorithms, software engineering, and systems design.",
        tag: "degree",
        views: 342000,
        interested: 56000,
        engaged: 15000,
    },
    {
        id: "D4",
        title: "Bachelor of Science in Agricultural Technology",
        subtitle: "University of Peradeniya",
        icon: "https://upload.wikimedia.org/wikipedia/en/c/cc/University_of_Peradeniya_crest.png",
        image: "https://www.carsu.edu.ph/sites/default/files/styles/555x255/public/caa/files/IMG_9171_0.jpg?itok=2ZaKx1Hy",
        description: "Combines agricultural sciences with modern technology for sustainable farming.",
        tag: "degree",
        views: 212000,
        interested: 47000,
        engaged: 12000,
    },
    {
        id: "D5",
        title: "Bachelor of Dental Surgery (BDS)",
        subtitle: "University of Peradeniya",
        icon: "https://upload.wikimedia.org/wikipedia/en/c/cc/University_of_Peradeniya_crest.png",
        image: "https://medicaltree.co.in/wp-content/uploads/2025/01/bds-bachelor-of-dental-surgery-mobile-banner-img.png",
        description: "Trains students in dentistry, oral surgery, and patient care.",
        tag: "degree",
        views: 189000,
        interested: 31000,
        engaged: 9000,
    },
    {
        id: "D6",
        title: "Bachelor of Business Administration (BBA)",
        subtitle: "University of Sri Jayewardenepura",
        icon: "https://thumbnail.imgbin.com/25/6/3/imgbin-university-of-sri-jayewardenepura-sri-jayawardenapura-kotte-university-of-colombo-vidyodaya-pirivena-university-of-moratuwa-campus-BBjmf2daAUKK6GD8v37fb0DW5_t.jpg",
        image: "https://saegis.ac.lk/wp-content/uploads/2023/09/l.jpg",
        description: "Focuses on finance, HR, marketing, and organizational behavior in a business context.",
        tag: "degree",
        views: 304000,
        interested: 54000,
        engaged: 16000,
    },
    {
        id: "D7",
        title: "Bachelor of Science in Environmental Science",
        subtitle: "University of Sri Jayewardenepura",
        icon: "https://thumbnail.imgbin.com/25/6/3/imgbin-university-of-sri-jayewardenepura-sri-jayawardenapura-kotte-university-of-colombo-vidyodaya-pirivena-university-of-moratuwa-campus-BBjmf2daAUKK6GD8v37fb0DW5_t.jpg",
        image: "https://wsu.ac.za/images/2024/07/24/bachelor-of-science-in-environmental-studies.jpg",
        description: "Covers ecology, pollution control, and sustainable resource management.",
        tag: "degree",
        views: 175000,
        interested: 29000,
        engaged: 7000,
    },
    {
        id: "D8",
        title: "Bachelor of Commerce in Marketing",
        subtitle: "University of Kelaniya",
        icon: "https://upload.wikimedia.org/wikipedia/en/e/e0/Kelaniya.png",
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSdo60bwBp3gJuqfQKWelcuYqQWAa0e3wVBCg&s",
        description: "Prepares students with strategic marketing, brand management, and digital skills.",
        tag: "degree",
        views: 198000,
        interested: 31000,
        engaged: 8000,
    },
    {
        id: "D9",
        title: "Bachelor of Arts in Mass Communication",
        subtitle: "University of Kelaniya",
        icon: "https://upload.wikimedia.org/wikipedia/en/e/e0/Kelaniya.png",
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT2e3po2_JyKWSxhM5M9vt1FDAzzggZAg-6sA&s",
        description: "Explores journalism, media ethics, public relations, and broadcasting.",
        tag: "degree",
        views: 164000,
        interested: 25000,
        engaged: 6000,
    }
];
