export const universitiesData = [
    {
        id: "U1",
        title: "University of Moratuwa",
        subtitle: "Moratuwa, Sri Lanka",
        enrollments: 125000,
        icon: "https://upload.wikimedia.org/wikipedia/en/6/60/University_of_Moratuwa_logo.png",
        image: "https://uom.lk/sites/default/files/civil/images/civil1_0.jpg",
        description: "Renowned for engineering, technology, and innovation, the University of Moratuwa is Sri Lanka’s top institution for STEM education and cutting-edge research.",
        tag: "university",
        mostViewed: [
            {
                id: "D1",
                title: "Bachelor of Science in Engineering Honours",
                image: "https://uom.lk/sites/default/files/civil/images/civil1_0.jpg",
                views: 578000,
                interested: 78000,
            },
            {
                id: "D2",
                title: "Bachelor of Science Honours in Artificial Intelligence",
                image: "https://uom.lk/sites/default/files/civil/images/civil1_0.jpg",
                views: 578000,
                interested: 78000,
            },
        ],
    },
    {
        id: "U2",
        title: "University of Colombo",
        subtitle: "Colombo, Sri Lanka",
        enrollments: 100000,
        icon: "https://upload.wikimedia.org/wikipedia/en/f/f9/Logo_of_the_University_of_Colombo.png",
        image: "https://capage.eu/wp-content/uploads/2024/04/Colombo_uni_02.jpg",
        description: "A prestigious institution offering a wide range of programs in law, medicine, science, and arts, the University of Colombo fosters academic excellence in the heart of the capital.",
        tag: "university",
        mostViewed: [
            {
                id: "D3",
                title: "Bachelor of Science in Computer Science",
                image: "https://dcfwfuaf91uza.cloudfront.net/residential/wp-content/uploads/Bachelor-of-Science-in-Computer-Science-General.jpg",
                views: 342000,
                interested: 56000,
            },
            {
                id: "D4",
                title: "Bachelor of Law",
                image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSmxehgYOh-DKY9DYpAnoPGG6JFCK1uGVt14g&s",
                views: 294000,
                interested: 39000,
            },
        ],
    },
    {
        id: "U3",
        title: "University of Peradeniya",
        subtitle: "Peradeniya, Sri Lanka",
        enrollments: 95000,
        icon: "https://upload.wikimedia.org/wikipedia/en/c/cc/University_of_Peradeniya_crest.png",
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRYz126u0Z3sDbGQWYRZVVmvzyXz4OFPgUTrQ&s",
        description: "Nestled in the hills, the University of Peradeniya is celebrated for its lush campus, heritage, and excellence in medicine, agriculture, and engineering.",
        tag: "university",
        mostViewed: [
            {
                id: "D5",
                title: "Bachelor of Science in Agricultural Technology",
                image: "https://www.carsu.edu.ph/sites/default/files/styles/555x255/public/caa/files/IMG_9171_0.jpg?itok=2ZaKx1Hy",
                views: 212000,
                interested: 47000,
            },
            {
                id: "D6",
                title: "Bachelor of Dental Surgery (BDS)",
                image: "https://medicaltree.co.in/wp-content/uploads/2025/01/bds-bachelor-of-dental-surgery-mobile-banner-img.png",
                views: 189000,
                interested: 31000,
            },
        ],
    },
    {
        id: "U4",
        title: "University of Sri Jayewardenepura",
        subtitle: "Nugegoda, Sri Lanka",
        enrollments: 89000,
        icon: "https://thumbnail.imgbin.com/25/6/3/imgbin-university-of-sri-jayewardenepura-sri-jayawardenapura-kotte-university-of-colombo-vidyodaya-pirivena-university-of-moratuwa-campus-BBjmf2daAUKK6GD8v37fb0DW5_t.jpg",
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRiP_NQZm_V1YqTOxJE2nObDsVv_eh1Wesfkg&s",
        description: "A leader in management, social sciences, and natural sciences, the University of Sri Jayewardenepura drives impactful research and entrepreneurship.",
        tag: "university",
        mostViewed: [
            {
                id: "D7",
                title: "Bachelor of Business Administration (BBA)",
                image: "https://saegis.ac.lk/wp-content/uploads/2023/09/l.jpg",
                views: 304000,
                interested: 54000,
            },
            {
                id: "D8",
                title: "Bachelor of Science in Environmental Science",
                image: "https://wsu.ac.za/images/2024/07/24/bachelor-of-science-in-environmental-studies.jpg",
                views: 175000,
                interested: 29000,
            },
        ],
    },
    {
        id: "U5",
        title: "University of Kelaniya",
        subtitle: "Kelaniya, Sri Lanka",
        enrollments: 72000,
        icon: "https://upload.wikimedia.org/wikipedia/en/e/e0/Kelaniya.png",
        image: "https://science.kln.ac.lk/images/2020/07/23/fos_image.jpg",
        description: "Recognized for its rich academic heritage, the University of Kelaniya specializes in humanities, business, and emerging tech fields.",
        tag: "university",
        mostViewed: [
            {
                id: "D9",
                title: "Bachelor of Arts in Mass Communication",
                image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT2e3po2_JyKWSxhM5M9vt1FDAzzggZAg-6sA&s",
                views: 164000,
                interested: 25000,
            },
            {
                id: "D10",
                title: "Bachelor of Commerce in Marketing",
                image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSdo60bwBp3gJuqfQKWelcuYqQWAa0e3wVBCg&s",
                views: 198000,
                interested: 31000,
            },
        ],
    },
];
